version: '3.8'
services:
  react_musicplayer:
    image: levidocker123/react_musicplayer_docker:latest
    container_name: react_musicplayer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    
  