version: '3.8'
services:
  react-playmusic-app:
    image: levidocker123/react-playmusic-app:latest
    container_name: react-playmusic-app
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8080/api/
    ports:
      - 8081:80
    
  